# Generated by Django 2.1.4 on 2020-01-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songplays',
            fields=[
                ('songplay_id', models.TextField(primary_key=True, serialize=False)),
                ('start_time', models.BigIntegerField(blank=True)),
                ('song_id', models.TextField(blank=True)),
                ('artist_id', models.TextField(blank=True)),
                ('session_id', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'songplays',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('level', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='songplays',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Users'),
        ),
    ]
